<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishAot>true</PublishAot>
    <ServerGarbageCollection>false</ServerGarbageCollection>
	<StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ZstdSharp.Port" Version="0.8.8" />
    <Content Update="gateway.local.json" CopyToOutputDirectory="Never" CopyToPublishDirectory="Never" />
  </ItemGroup>

</Project>
